
# capture-ffi/Cargo.toml
[package]
name = "xcap-c-api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Compile to a dynamic library (.so, .dll, .dylib)

[dependencies]
xcap = "0.1.0" # Use an appropriate version
libc = "0.2"
